name: GitHub pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4.0.0
        with:
          version: latest
          run_install: true

      - name: Install doc theme
        run: pnpm i -g typedoc-github-theme

      - name: Build
        uses: bengreenier/tsdoc-action@v1.1-alpha.1
        with:
          source_dir: ./packages/react-user-media/*
          output_dir: ./docs_out
          plugin: typedoc-github-theme
          tsconfig: ./packages/react-user-media/tsconfig.lib.json
          front_page: ./packages/react-user-media/README.md

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_out
          
